; File initially autogenerated by ./scripts/dump_tilesets.py

SECTION "Tileset MainText", ROMX[$5D28], BANK[$01]
TilesetMainText::
  INCBIN "./build/gfx/tilesets/MainText.2bpp"
SECTION "Tileset MainText End", ROMX[$6B27], BANK[$01]

