; Autogenerated by ./scripts/dump_scripts.py

MACRO Unknown00
  db $00 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown01
  db $01 | (\1 << 7)
  db \2
  ENDM

MACRO LoadSceneText
  db $02 | (\1 << 7)
  db \2
  db \3
  ENDM

MACRO Unknown03
  db $03 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown04
  db $04 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown05
  db $05 | (\1 << 7)
  db \2
  ENDM

MACRO CharacterMove
  db $06 | (\1 << 7)
  db \2
  db \3
  db \4
  ENDM

MACRO Unknown07
  db $07 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown08
  db $08 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown09
  db $09 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown0A
  db $0A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown0B
  db $0B | (\1 << 7)
  db \2
  db \3
  db \4
  ENDM

MACRO Unknown0C
  db $0C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown0D
  db $0D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown0E
  db $0E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown0F
  db $0F | (\1 << 7)
  db \2
  db \3
  ENDM

MACRO Unknown10
  db $10 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown11
  db $11 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown12
  db $12 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown13
  db $13 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown14
  db $14 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown15
  db $15 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown16
  db $16 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown17
  db $17 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown18
  db $18 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown19
  db $19 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1A
  db $1A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1B
  db $1B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1C
  db $1C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1D
  db $1D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1E
  db $1E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown1F
  db $1F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown20
  db $20 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown21
  db $21 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown22
  db $22 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown23
  db $23 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown24
  db $24 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown25
  db $25 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown26
  db $26 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown27
  db $27 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown28
  db $28 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown29
  db $29 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2A
  db $2A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2B
  db $2B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2C
  db $2C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2D
  db $2D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2E
  db $2E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown2F
  db $2F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown30
  db $30 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown31
  db $31 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown32
  db $32 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown33
  db $33 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown34
  db $34 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown35
  db $35 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown36
  db $36 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown37
  db $37 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown38
  db $38 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown39
  db $39 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3A
  db $3A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3B
  db $3B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3C
  db $3C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3D
  db $3D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3E
  db $3E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown3F
  db $3F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown40
  db $40 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown41
  db $41 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown42
  db $42 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown43
  db $43 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown44
  db $44 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown45
  db $45 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown46
  db $46 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown47
  db $47 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown48
  db $48 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown49
  db $49 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4A
  db $4A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4B
  db $4B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4C
  db $4C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4D
  db $4D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4E
  db $4E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown4F
  db $4F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown50
  db $50 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown51
  db $51 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown52
  db $52 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown53
  db $53 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown54
  db $54 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown55
  db $55 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown56
  db $56 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown57
  db $57 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown58
  db $58 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown59
  db $59 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5A
  db $5A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5B
  db $5B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5C
  db $5C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5D
  db $5D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5E
  db $5E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown5F
  db $5F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown60
  db $60 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown61
  db $61 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown62
  db $62 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown63
  db $63 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown64
  db $64 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown65
  db $65 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown66
  db $66 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown67
  db $67 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown68
  db $68 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown69
  db $69 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6A
  db $6A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6B
  db $6B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6C
  db $6C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6D
  db $6D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6E
  db $6E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown6F
  db $6F | (\1 << 7)
  db \2
  ENDM

MACRO Unknown70
  db $70 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown71
  db $71 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown72
  db $72 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown73
  db $73 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown74
  db $74 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown75
  db $75 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown76
  db $76 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown77
  db $77 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown78
  db $78 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown79
  db $79 | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7A
  db $7A | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7B
  db $7B | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7C
  db $7C | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7D
  db $7D | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7E
  db $7E | (\1 << 7)
  db \2
  ENDM

MACRO Unknown7F
  db $7F | (\1 << 7)
  db \2
  ENDM

